### ISSUE TITLE
Stuck at relocate image success!

### ISSUE THREAD

**Issue by DXXNS** [KANKOSHEV/face-injector-v2#18]
I have a small issue..
The injector is stuck on:
driver initialized!

process_id: 0x4528
thread_id: 0x4e80
allocate_base: 0x000002538C780000
relocate image success!

I am using the injector for polygon. The window class is UnrealWindow
The Cheat is a polygon cheat.
My operating system is windows 11

**Comment by RaphielHS** [comment]
How did you manage it to get to "driver initialized!"? Im on Windows 11 too and still stuck on "driver initialize error =<"

**Comment by DXXNS** [comment]
> How did you manage it to get to "driver initialized!"? Im on Windows 11 too and still stuck on "driver initialize error =<"

I somehow fixed it.. try using the fixed version

**Comment by DXXNS** [comment]
Bruh still the same problem

**Comment by DXXNS** [comment]
Ahhhh i fixed it

**Comment by DXXNS** [comment]
If you need help add me on discord DXXNS#2620
